### ISSUE TITLE
Error position is incorrect when tests fail

### ISSUE THREAD

**Issue by behrang** [ton-org/blueprint#11]
If a test fails, the error line and column is wrong and the displayed source code shows the incorrect snippet from the file.

It looks like that there is a problem with source map or ts-jest, but I can't figure out a solution to fix it.

To recreate the error, create an example project, create a contract based on the counter template, then add an artificial error to one of the tests and run `yarn blueprint test`. I added `throw new Error();` to the first line of `should increase counter` test case and here is the output that I get:

```
yarn run v1.22.19
$ /Users/x/Desktop/example/node_modules/.bin/blueprint test

> example@0.0.1 test
> jest

 FAIL  tests/HelloWorld.spec.ts
  HelloWorld
    ✓ should deploy (1326 ms)
    ✕ should increase counter (1 ms)

  ● HelloWorld › should increase counter



      26 |
      27 |         const deployer = await blockchain.treasury('deployer');
    > 28 |
         | ^
      29 |         const deployResult = await helloWorld.sendDeploy(deployer.getSender(), toNano('0.05'));
      30 |
      31 |         expect(deployResult.transactions).toHaveTransaction({

      at Object.<anonymous> (tests/HelloWorld.spec.ts:28:15)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        4.514 s, estimated 6 s
Ran all test suites.
Error: Command failed: npm test
    at checkExecSyncError (node:child_process:841:11)
    at execSync (node:child_process:912:15)
    at test (/Users/x/Desktop/example/node_modules/@ton-community/blueprint/dist/cli/test.js:7:34)
    at main (/Users/x/Desktop/example/node_modules/@ton-community/blueprint/dist/cli/cli.js:36:11)
    at Object.<anonymous> (/Users/x/Desktop/example/node_modules/@ton-community/blueprint/dist/cli/cli.js:41:1)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 57761,
  stdout: null,
  stderr: null
}
✨  Done in 6.46s.
```

**Comment by krigga** [comment]
After a long string of investigation, I found the underlying issue: it's the fact that jest installs source-map-support when running tests, but the `compile` function from blueprint registers `ts-node` (to import .ts files), which installs source-map-support of its own, and they seem to be conflicting with each other, messing with the source maps.

One way to fix it as I see it (there could be others) is to turn off the source-map-support of ts-node, and there's a pending issue for that: https://github.com/TypeStrong/ts-node/issues/796

I might submit a PR to ts-node to fix it, which will in turn allow to fix this.

**Comment by behrang** [comment]
Thanks. Is there any workaround for now?

**Comment by krigga** [comment]
There kind of is, but it's really more of a hack than anything else, and might (probably will) mess with your source maps elsewhere. However if it's only tests that matter, you can open `node_modules/ts-node/dist/index.js` and comment out the line that installs source map support (ctrl+f `sourcemap` should do the trick), but once again, this is a major hack and is very likely to mess with your source maps in things other than tests (deploy scripts etc.)

**Comment by Alejandbel** [comment]
Closing as workaround founded
