### ISSUE TITLE
Error when deploy contract

### ISSUE THREAD

**Issue by kuchaguangjie** [ton-org/blueprint#160]
Error msg:
```
Connected to wallet at address: EQD6BVNuYtgiaSFZLPVW9YmBuHtVje62GDZXJ7ZM-4JbM767
Error: Received error: ""
    at HttpApi.doCall (/mnt/star/git_repos/ton_repos/ton-learn/node_modules/.pnpm/@ton+ton@15.1.0_@ton+core@0.59.0_@ton+crypto@3.3.0__@ton+crypto@3.3.0/node_modules/@ton/ton/dist/client/api/HttpApi.js:274:19)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async TonClient.getContractState (/mnt/star/git_repos/ton_repos/ton-learn/node_modules/.pnpm/@ton+ton@15.1.0_@ton+core@0.59.0_@ton+crypto@3.3.0__@ton+crypto@3.3.0/node_modules/@ton/ton/dist/client/TonClient.js:233:20)
    at async Object.getState (/mnt/star/git_repos/ton_repos/ton-learn/node_modules/.pnpm/@ton+ton@15.1.0_@ton+core@0.59.0_@ton+crypto@3.3.0__@ton+crypto@3.3.0/node_modules/@ton/ton/dist/client/TonClient.js:340:25)
    at async WrappedContractProvider.getState (/mnt/star/git_repos/ton_repos/ton-learn/node_modules/.pnpm/@ton+blueprint@0.25.0_@ton+core@0.59.0_@ton+crypto@3.3.0__@ton+crypto@3.3.0_@ton+ton@15.1.0_@_n3sea5pkyctyuns6bo2etne2bu/node_modules/@ton/blueprint/dist/network/createNetworkProvider.js:77:16)
    at async WrappedContractProvider.internal (/mnt/star/git_repos/ton_repos/ton-learn/node_modules/.pnpm/@ton+blueprint@0.25.0_@ton+core@0.59.0_@ton+crypto@3.3.0__@ton+crypto@3.3.0_@ton+ton@15.1.0_@_n3sea5pkyctyuns6bo2etne2bu/node_modules/@ton/blueprint/dist/network/createNetworkProvider.js:86:91)
    at async TonLearn.sendDeploy (/mnt/star/git_repos/ton_repos/ton-learn/wrappers/TonLearn.ts:30:9)
    at async Object.run (/mnt/star/git_repos/ton_repos/ton-learn/scripts/deployTonLearn.ts:16:5)
    at async run (/mnt/star/git_repos/ton_repos/ton-learn/node_modules/.pnpm/@ton+blueprint@0.25.0_@ton+core@0.59.0_@ton+crypto@3.3.0__@ton+crypto@3.3.0_@ton+ton@15.1.0_@_n3sea5pkyctyuns6bo2etne2bu/node_modules/@ton/blueprint/dist/cli/run.js:25:5)
    at async main (/mnt/star/git_repos/ton_repos/ton-learn/node_modules/.pnpm/@ton+blueprint@0.25.0_@ton+core@0.59.0_@ton+crypto@3.3.0__@ton+crypto@3.3.0_@ton+ton@15.1.0_@_n3sea5pkyctyuns6bo2etne2bu/node_modules/@ton/blueprint/dist/cli/cli.js:91:5)
```

I try to deploy to testnet, and use tonkeeper to scan the qr code.
The error msg is empty ...

**Comment by kunaldhongade** [comment]
I have also facing these error while deploying my smart func smart contract on ton please help


```
 tonique (main) ✗ npx blueprint run  
 
? Choose file to use (Use arrow keys)
? Choose file to use deployNewListing
? Which network do you want to use? 
? Which network do you want to use? testnet
? Which wallet are you using? (Use arrow keys)
? Which wallet are you using? TON Connect compatible mobile wallet (example: Tonkeeper)
Connected to wallet at address: EQAn70DlO3aJrJdBDO8K_Z5IE9BytI2xreEDQjiZLKaIRmjg
Sending transaction. Approve in your wallet...[TON_CONNECT_SDK] Send http-bridge request: {
  method: 'sendTransaction',
  params: [
    '{"messages":[{"address":"EQCTWa3pAih1oT_a5Y8hfGI_bRUYzMAm5wL5Bvxhjfnrixlc","amount":"50000000","payload":"te6cckEBAQEAAgAAAEysuc0=","stateInit":"te6cckECHAEAAg0AAgE0ARsBFP8A9KQT9LzyyAsCAgFiAxQCAssEBwLp0MyLHAJJfA+DQ0wMBcbCSXwPg8Bb6QDAg8B0C0x/TPzEhghBEZXAguo4gWyCCEDuaygC+8uBlIfAYAqD4I4IICTqAoFi2CfAZ8BfgMiCCEFJnaXO6lVvwG/AX4CCCEERkdWO64wIxghBSZWYguuMCMIQP8vCBQYAkjAh+QH4QoEBC/QOb6Ex8uBm+kD6ADAh8BhTEr7y4Gf4IwG58uBoIYIK+vCAoRTwHBKhIMIAmoIK+vCAoVIQ8ByRMOJwIPAZ8BcANCDwGDAgwgDy4GeCCvrwgKFSEPAccCDwGfAXAgEgCAsCAfQJCgAdO1E0PQEAfhh9AQB+GLRgABk+EL4Qcj0APQAye1UgAgEgDBECASANEAIBIA4PACs+QH4QYEBC/QOb6GV+gDTPzDgMHAggACUyFj6Ass/AfkB+EGBAQv0Q/hhgACFXHIywAB+QH4QoEBC/RD+GKAIBSBITACccIAQyMsFUAPPFgH6AstqyXH7AIABLCDwGCHCAI4Z+CMBvo4Qggr68IChUhDwHHAg8BnwF5Fb4pJfA+KACASAVGAIBIBYXACW4GB8BbwGDH4IyG+kjBw4PgjoYAA269m8BbwGIAgFmGRoAEbAKIIQO5rKAIAAhs/h8Bb5AfhCgQEL9A5voTGAAEAAAIyoAAAAARmpFwA=="}],"valid_until":1734604414701,"from":"0:27ef40e53b7689ac97410cef0afd9e4813d072b48db1ade1034238992ca68846","network":"-3"}'
  ],
  id: '5'
}
[TON_CONNECT_SDK] Wallet message received: { error: { code: 0, message: 'Context must be an Activity' }, id: 5 }
UnknownError: [TON_CONNECT_SDK_ERROR] UnknownError
Context must be an Activity
    at SendTransactionParser.parseAndThrowError (/home/kunal/code/Ton/tonique/node_modules/@tonconnect/sdk/src/parsers/send-transaction-parser.ts:38:15)
    at TonConnect.<anonymous> (/home/kunal/code/Ton/tonique/node_modules/@tonconnect/sdk/src/ton-connect.ts:254:42)
    at Generator.next (<anonymous>)
    at fulfilled (/home/kunal/code/Ton/tonique/node_modules/node_modules/tslib/tslib.es6.js:71:58)
```

**Comment by Alejandbel** [comment]
Please, provide steps to reproduce

**Comment by Alejandbel** [comment]
Closing as irrelevant.
Feel free to reopen if you believe this needs further discussion.
