### ISSUE TITLE
problem with build to ts

### ISSUE THREAD

**Issue by StrongerProgrammer7** [ton-org/blueprint#88]
I don't know if it's related to the blueprint, but I think it is. After building my contract, everything goes well and so does the deployment.

I want to send an address to a function (I tried also to send to simple functions, just empty ones that take an address as an argumentnet).

Function in contract:
```
get fun ContractPatient(owner: Address): Address
    {
        return contractAddress(initOf Patient(myAddress(),owner));
    }
```

In react js , vite:
```
     const patient = useAsyncInitialize(async () =>
    {
        if (!patientsContract || !client) return;
        console.log(patientsContract);

        const addr = await patientsContract.getContractPatient(
            Address.parse(wallet)
        )

        return client.open(Patient.fromAddress(addr))
    }, [patientsContract, client])

```

And I get the following error, what could this be related to? 
```
Uncaught (in promise) Error: Invalid address. Got EQD47c2WNNyLqSVPS0-x6DiAjWx1EzB_FVqwSThYKeI2Fe34
    at BitBuilder.writeAddress (BitBuilder.js:266:15)
    at _Builder.storeAddress (Builder.js:237:20)
    at TupleBuilder.writeAddress (builder.js:102:80)
    at Patients.getContractPatient (tact_Patients.ts:711:17)
    at Proxy.<anonymous> (openContract.js:38:47)
    at useIntegrationContract.js:29:45
    at useAsyncInitialize.js:11:28
    at useAsyncInitialize.js:12:11
    at commitHookEffectListMount (react-dom_client.js:24344:34)
    at commitPassiveMountOnFiber (react-dom_client.js:25592:19)
```

I'm using JS. Blueprint test < it's OK! Example (Success.)
```
it('reg', async () =>
    {
        const message: Registration =
        {
            $$type: 'Registration',
            address: deployer.address.toString()
        }

        await patients.send(deployer.getSender(),
            {
                value: toNano("0.5")
            }, message);

        const addressContract = await patients.getContractPatient(deployer.address);
        const patient = blockchain.openContract(Patient.fromAddress(addressContract));

        console.log((await patient.getAllDocs()).values());
        expect((await patient.getAllDocs()).values().length === 0);
    });
```
    
I try

I also have a method that returns String. Blueprint test is ok. There is an error on the client again, analog Map. I think have problem with compile to TS after blueprint build
```
Uncaught (in promise) Error: Not a cell: null
    at _TupleReader.readCell (reader.js:101:19)
    at _TupleReader.readString (reader.js:157:22)
    at Patient.getAllDocs (tact_Patient.ts:724:29)
    at async onClick (App.tsx:44:32)
```

**Comment by 0xDmitry** [comment]
I have similar error using Next and TypeScript

```
Uncaught (in promise) Error: Invalid address. Got EQDmjTeoKRxPsT5Qpt16A8VVqqBeWr9Z_579_W399FNuTsmD
    at BitBuilder.writeAddress (BitBuilder.js:257:15)
    at Builder.storeAddress (Builder.js:237:20)
    at eval (tact_PlayerStats.ts:788:13)
    at PlayerStats_init (tact_PlayerStats.ts:799:80)
    at PlayerStats.init (tact_PlayerStats.ts:870:22)
    at eval (usePlayerStats.ts:31:36)
    at eval (useAsyncInitialize.ts:12:22)
    at eval (useAsyncInitialize.ts:13:5)
```

**Comment by Alejandbel** [comment]
Issue not connected with blueprint. Please, make sure that you are using same version of @ton/ton and @ton/core libraries
